name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main  # Run CI when a PR is opened to main
  push:
    branches:
      - main  # Run CD when changes are merged into main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: pytest

  build-and-push:
    name: Build & Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: test  # Run this job only if tests pass

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t mubaraktoye/fastapi-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push mubaraktoye/fastapi-app:latest
