name: Build and deploy container app to Azure Web App - bookfastapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest  # Ensure tests pass before deployment

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.AzureAppService_ContainerUsername_1dc4640df24e4eb4a94537c0b726995b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_731f1d9f7ba1465e88a392c16d9046db }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mubaraktoye/fastapi-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bookfastapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_241f2caf30f544699a40421f8223a5f2 }}
        images: mubaraktoye/fastapi-app:${{ github.sha }}

    - name: Restart Azure Web App
      run: |
        az webapp restart --name bookfastapi --resource-group DefaultResourceGroup-CUS
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
